# Generated by Django 4.1.7 on 2023-02-27 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regist_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='リダイレクトカウント')),
                ('regist_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 27, 23, 5, 26, 608835), null=True, verbose_name='日時')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='リダイレクトカウント')),
                ('my_shorturl', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='短縮URL')),
                ('my_seturl', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='設定URL')),
                ('my_seturl_hist', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='設定URLの履歴')),
                ('redirect_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='リダイレクトカウント')),
            ],
        ),
    ]
