# Generated by Django 4.1.7 on 2023-02-28 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0002_regist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regist_table',
            name='regist_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 28, 22, 59, 40, 660331), null=True, verbose_name='日時'),
        ),
    ]
