# Generated by Django 4.1.7 on 2023-03-04 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0005_alter_regist_table_regist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='qrimg_id')),
                ('regist_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 15, 26, 43, 142479), null=True, verbose_name='日時')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='regist_table',
            name='regist_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 15, 26, 43, 142479), null=True, verbose_name='日時'),
        ),
    ]
