# Generated by Django 4.1.7 on 2023-03-04 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_qr', '0018_alter_regist_table_regist_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist_table',
            name='text',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='テキスト'),
        ),
        migrations.AddField(
            model_name='regist_table',
            name='title',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='regist_table',
            name='regist_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 23, 12, 46, 381016), null=True, verbose_name='日時'),
        ),
        migrations.AlterField(
            model_name='temp_image',
            name='regist_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 4, 23, 12, 46, 381016), null=True, verbose_name='日時'),
        ),
    ]
